version: '3'

services:
  news-bot:
    build: .
    environment:
      - GOOGLE_NEWS_API_KEY_1=${GOOGLE_NEWS_API_KEY_1}
      - GOOGLE_NEWS_API_KEY_2=${GOOGLE_NEWS_API_KEY_2}
      - GOOGLE_NEWS_API_KEY_3=${GOOGLE_NEWS_API_KEY_3}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
    volumes:
      - .:/app
